name: Generate Streak Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DenverCoder1/github-readme-streak-stats@v1
        with:
          user: ${{ github.repository_owner }}
